name: Rebase on Upstream

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - uses: ytdl-org/ytdl-patched-rebase-upstream-action@master
      with:
        token: ${{ secrets.GH_PAT }}
        upstream: ytdl-org/youtube-dl
